In [2]:
import pandas as pd
import numpy as np

In [6]:
#Creating a Series
s = pd.Series( [10, 20, 30, 40], index=['a', 'b', 'c', 'd'] )
print("Series:")
print(s)
print(f"Value at index 'c': {s['c']}")

Series:
a    10
b    20
c    30
d    40
dtype: int64
Value at index 'c': 30

In [95]:
#Creating a Dataframe
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Andrea', 'Jack', 'Julie', 'Paul', 'Rosie'],
    'Age': [25, 32, 19, 29, 22, 34, 34, 35, 32],
    'Salary': [5000, 68000, 75000, 62000, 12000, 34000, 234440, 237890, 12000],
    'Department': ['HR', 'IT', 'IT', 'Marketing', 'HR', 'IT', 'Marketing', 'IT', 'IT'],
    'City': ['NewYork', 'Paris', 'Tokyo', 'Florida', 'NewYork', 'Seoul', 'Sofia', 'Sydney', 'Toronto'],
}
df = pd.DataFrame(data)
print("DataFrame:")
print(df)
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.info())
print(df.head())
print(df.tail(3))
print(df.describe())

DataFrame:
      Name  Age  Salary Department     City
0    Alice   25    5000         HR  NewYork
1      Bob   32   68000         IT    Paris
2  Charlie   19   75000         IT    Tokyo
3    Diana   29   62000  Marketing  Florida
4   Andrea   22   12000         HR  NewYork
5     Jack   34   34000         IT    Seoul
6    Julie   34  234440  Marketing    Sofia
7     Paul   35  237890         IT   Sydney
8    Rosie   32   12000         IT  Toronto
(9, 5)
Index(['Name', 'Age', 'Salary', 'Department', 'City'], dtype='object')
Name          object
Age            int64
Salary         int64
Department    object
City          object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        9 non-null      object
 1   Age         9 non-null      int64
 2   Salary      9 non-null      int64
 3   Department  9 non-null      object
 4   City        9 non-null      object
dtypes: int64(2), object(3)
memory usage: 492.0+ bytes
None
      Name  Age  Salary Department     City
0    Alice   25    5000         HR  NewYork
1      Bob   32   68000         IT    Paris
2  Charlie   19   75000         IT    Tokyo
3    Diana   29   62000  Marketing  Florida
4   Andrea   22   12000         HR  NewYork
    Name  Age  Salary Department     City
6  Julie   34  234440  Marketing    Sofia
7   Paul   35  237890         IT   Sydney
8  Rosie   32   12000         IT  Toronto
             Age         Salary
count   9.000000       9.000000
mean   29.111111   82258.888889
std     5.797509   90978.735489
min    19.000000    5000.000000
25%    25.000000   12000.000000
50%    32.000000   62000.000000
75%    34.000000   75000.000000
max    35.000000  237890.000000

In [96]:
#Select a single column ( returns a Series)
ages = df['Age']
print(ages)

0    25
1    32
2    19
3    29
4    22
5    34
6    34
7    35
8    32
Name: Age, dtype: int64

In [93]:
#Selct multuiple columns (returns a DataFrame)
subset= df[['Name', 'City']]
print(subset)

      Name      City
0    Alice   NewYork
1      Bob     Paris
2  Charlie     Tokyo
3    Diana   Florida
4   Andrea   NewYork
5     Jack     Seoul
6    Julie     Sofia
7     Paul    Sydney
8    Rosie  Toronoto

In [94]:
df.iloc[6:10,[0,3]]

    Name Department
6  Julie  Marketing
7   Paul         IT
8  Rosie         IT

In [ ]:
# Find all students older than 28
older_students = df [df ['Age' ] > 28]

# Multiple conditions (use & for AND, | for OR)
# Students older than 25 AND from London
filtered = df [(df ['Age'] > 25) & (df ['City' ] == 'London' )]

# Students younger than 30 OR from Paris
filtered = df[(df['Age'] < 30) | (df ['City'] == 'Paris')]

# Check for missing values
missing_ages = df [df ['Age' ]. isna() ]

In [80]:
TASK = df[(df ['Age' ] 25) & (df['Department'] == 'IT')]
print(TASK)

      Name  Age  Salary Department      City
1      Bob   32   68000         IT     Paris
2  Charlie   37   75000         IT     Tokyo
5     Jack   34   34000         IT     Seoul
7     Paul   35  237890         IT    Sydney
8    Rosie   32   12000         IT  Toronoto

In [83]:
df ["Orgin_Country"] = ["China", "Nepal", "Bangladesh", "India", "France", "Turkey", "Canada", "Japan", "Russia"]

In [87]:
df["Age_category"] = df["Age"].apply(
    lambda x: "Young" if x < 20 else "Middle"
)

In [88]:
df

      Name  Age  Salary Department      City Orgin_Country Age_category
0    Alice   25    5000         HR   NewYork         China       Middle
1      Bob   32   68000         IT     Paris         Nepal       Middle
2  Charlie   37   75000         IT     Tokyo    Bangladesh       Middle
3    Diana   29   62000  Marketing   Florida         India       Middle
4   Andrea   22   12000         HR   NewYork        France       Middle
5     Jack   34   34000         IT     Seoul        Turkey       Middle
6    Julie   34  234440  Marketing     Sofia        Canada       Middle
7     Paul   35  237890         IT    Sydney         Japan       Middle
8    Rosie   32   12000         IT  Toronoto        Russia       Middle

In [ ]:
df.isna()
df.isna().sum()

# Drop missing values
df_clean = df.dropna()
df_clean = df.dropna(subset=['age'])

# Fill missing values
df_filled = df.fillna(0)
df_filled = df.fillna({'age': df['age'].mean()}) # Fill age with mean
df_filled = df ['age'].fillna(df ['age'].median()) # Fill series with median